#!/usr/bin/env python3
"""
inventory_template.py — read a PowerPoint template (.potx or .pptx) and print a
Markdown inventory of its masters, layouts and placeholders, ready to paste into
the project's DECK-SYSTEM.md.

  python3 inventory_template.py path/to/Template.potx            # markdown to stdout
  python3 inventory_template.py path/to/Template.potx --json     # machine-readable

Needs: python-pptx.  python-pptx refuses .potx by content type, so the file is
copied to a temp .pptx with the presentation part re-typed — read-only, the
template on disk is never touched.
"""
from __future__ import annotations
import json
import os
import shutil
import sys
import tempfile
import zipfile

POTX_CT = "application/vnd.openxmlformats-officedocument.presentationml.template.main+xml"
PPTX_CT = "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"


def as_pptx(path: str) -> str:
    """Return a path python-pptx can open. .pptx passes through; .potx is
    re-typed into a temp copy."""
    if not path.lower().endswith(".potx"):
        return path
    tmp = tempfile.mkdtemp(prefix="deck-")
    out = os.path.join(tmp, os.path.basename(path)[:-5] + ".pptx")
    with zipfile.ZipFile(path) as zin, zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "[Content_Types].xml":
                data = data.replace(POTX_CT.encode(), PPTX_CT.encode())
            zout.writestr(item, data)
    return out


def ph_kind(ph) -> str:
    t = str(ph.placeholder_format.type)
    return t.split(".")[-1].split(" ")[0].lower()   # "body", "title", "picture", "object", "slide_number"


def inventory(path: str) -> dict:
    from pptx import Presentation
    prs = Presentation(as_pptx(path))
    fonts = set()
    masters = []
    for m in prs.slide_masters:
        theme_name = None
        try:
            theme_part = m.part.part_related_by(
                "http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme")
            from lxml import etree
            root = etree.fromstring(theme_part.blob)
            ns = {"a": "http://schemas.openxmlformats.org/drawingml/2006/main"}
            theme_name = root.get("name")
            for tag in ("majorFont", "minorFont"):
                el = root.find(f".//a:{tag}/a:latin", ns)
                if el is not None:
                    fonts.add(el.get("typeface"))
        except Exception:
            pass
        layouts = []
        for lay in m.slide_layouts:
            phs = []
            for ph in lay.placeholders:
                f = ph.placeholder_format
                phs.append({"name": ph.name, "idx": f.idx, "kind": ph_kind(ph)})
            layouts.append({"name": lay.name, "placeholders": phs})
        masters.append({"name": theme_name or m.name or f"Master {len(masters)+1}",
                        "layouts": layouts})
    return {"template": os.path.basename(path), "masters": masters,
            "theme_fonts": sorted(fonts),
            "slide_width_in": round(prs.slide_width / 914400, 3),
            "slide_height_in": round(prs.slide_height / 914400, 3)}


def to_markdown(inv: dict) -> str:
    out = [f"<!-- generated by inventory_template.py from {inv['template']} — regenerate, don't hand-edit -->",
           f"Slide size: {inv['slide_width_in']} × {inv['slide_height_in']} in · theme fonts: "
           + ", ".join(inv["theme_fonts"] or ["(none declared)"]), ""]
    same = all(
        [l["name"] for l in m["layouts"]] == [l["name"] for l in inv["masters"][0]["layouts"]]
        for m in inv["masters"])
    out.append("### Masters\n")
    out.append("| # | Master | Layouts |")
    out.append("|---|---|---|")
    for i, m in enumerate(inv["masters"], 1):
        out.append(f"| {i} | {m['name']} | {len(m['layouts'])} |")
    out.append("")
    shown = inv["masters"][:1] if same else inv["masters"]
    if same and len(inv["masters"]) > 1:
        out.append("All masters carry the same layout set, shown once:\n")
    for m in shown:
        if not same:
            out.append(f"### Layouts — {m['name']}\n")
        else:
            out.append("### Layouts\n")
        out.append("| Layout | Placeholders (name · kind) |")
        out.append("|---|---|")
        for l in m["layouts"]:
            cells = " · ".join(f"`{p['name']}` {p['kind']}" for p in l["placeholders"]
                               if p["kind"] != "slide_number") or "—"
            out.append(f"| {l['name']} | {cells} |")
        out.append("")
    return "\n".join(out)


def main(argv):
    if len(argv) < 2 or argv[1] in ("-h", "--help"):
        print(__doc__); return 0
    inv = inventory(argv[1])
    if "--json" in argv:
        print(json.dumps(inv, indent=2, ensure_ascii=False))
    else:
        print(to_markdown(inv))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
